# Generated by Django 5.0.6 on 2024-08-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='grade',
            field=models.CharField(blank=True, choices=[('5', 'Відмінно'), ('4', 'Добре'), ('3', 'Нормально'), ('2', 'Не добре'), ('1', 'Жахливо')], max_length=20, null=True, verbose_name='Оцінка'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(verbose_name='Ваш можливий відгук'),
        ),
    ]
