# Generated by Django 5.0.6 on 2024-08-22 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_emails_viber_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='emails',
            name='telegram_number',
            field=models.TextField(blank=True, max_length=9, null=True, verbose_name='Номер Телеграм'),
        ),
    ]
