# Generated by Django 5.0.6 on 2024-08-27 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_emails_telegram_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=255, verbose_name='Прізвище')),
                ('email', models.EmailField(max_length=254, verbose_name='Електронна пошта')),
                ('phone', models.CharField(max_length=255, verbose_name='Контактний номер')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Покупець',
                'verbose_name_plural': 'Покупці',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Завершено')),
                ('shipping', models.BooleanField(default=True, verbose_name='Доставка')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.customer')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Список замовлень',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('addet_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered', to='shop.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product')),
            ],
            options={
                'verbose_name': 'Товар в замовленні',
                'verbose_name_plural': 'Товари в замовленні',
            },
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sity', models.CharField(choices=[('1', 'Умань'), ('2', 'Тальне'), ('3', 'Катеринопіль'), ('4', 'Христинівка'), ('5', 'Ульянівка'), ('6', 'Голованівськ')], max_length=255)),
                ('state', models.CharField(choices=[('1', 'Уманський'), ('2', 'Тальнівський'), ('3', 'Катеринопільський'), ('4', 'Христинівський'), ('5', 'Ульянівський'), ('6', 'Голованівський')], max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.customer')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.order')),
            ],
            options={
                'verbose_name': 'Адреса доставки',
                'verbose_name_plural': 'Адреси доставки',
            },
        ),
    ]
